package com.example.lcb.app.remote.ui

import com.example.lcb.app.R

/**
 * Maps packaged TV brand logo assets to IRDB brand folder names.
 * Regenerate this file with tools/download_tv_brand_logos.py when brand assets change.
 */
object BrandLogoResolver {
    private val logos = mapOf(
        "akai" to R.drawable.brand_logo_akai,
        "amazon" to R.drawable.brand_logo_amazon,
        "amazonbasics" to R.drawable.brand_logo_amazonbasics,
        "android" to R.drawable.brand_logo_android,
        "apex" to R.drawable.brand_logo_apex,
        "awa" to R.drawable.brand_logo_awa,
        "bauhn" to R.drawable.brand_logo_bauhn,
        "bbk" to R.drawable.brand_logo_bbk,
        "bgh" to R.drawable.brand_logo_bgh,
        "blaupunkt" to R.drawable.brand_logo_blaupunkt,
        "blitzwolf" to R.drawable.brand_logo_blitzwolf,
        "bose" to R.drawable.brand_logo_bose,
        "boulanger" to R.drawable.brand_logo_boulanger,
        "brandt" to R.drawable.brand_logo_brandt,
        "bush" to R.drawable.brand_logo_bush,
        "cadillac" to R.drawable.brand_logo_cadillac,
        "continentaledison" to R.drawable.brand_logo_continentaledison,
        "daewoo" to R.drawable.brand_logo_daewoo,
        "denver" to R.drawable.brand_logo_denver,
        "devant" to R.drawable.brand_logo_devant,
        "dual" to R.drawable.brand_logo_dual,
        "element" to R.drawable.brand_logo_element,
        "elements" to R.drawable.brand_logo_elements,
        "emerson" to R.drawable.brand_logo_emerson,
        "enseo" to R.drawable.brand_logo_enseo,
        "fetch" to R.drawable.brand_logo_fetch,
        "ffalcon" to R.drawable.brand_logo_ffalcon,
        "finlux" to R.drawable.brand_logo_finlux,
        "funai" to R.drawable.brand_logo_funai,
        "furrion" to R.drawable.brand_logo_furrion,
        "gigabyte" to R.drawable.brand_logo_gigabyte,
        "gogen" to R.drawable.brand_logo_gogen,
        "gpx" to R.drawable.brand_logo_gpx,
        "grundig" to R.drawable.brand_logo_grundig,
        "guesttek" to R.drawable.brand_logo_guesttek,
        "haier" to R.drawable.brand_logo_haier,
        "hisense" to R.drawable.brand_logo_hisense,
        "hitachi" to R.drawable.brand_logo_hitachi,
        "jvc" to R.drawable.brand_logo_jvc,
        "kogan" to R.drawable.brand_logo_kogan,
        "lg" to R.drawable.brand_logo_lg,
        "loewe" to R.drawable.brand_logo_loewe,
        "magnavox" to R.drawable.brand_logo_magnavox,
        "manta" to R.drawable.brand_logo_manta,
        "medion" to R.drawable.brand_logo_medion,
        "mivar" to R.drawable.brand_logo_mivar,
        "nec" to R.drawable.brand_logo_nec,
        "nevir" to R.drawable.brand_logo_nevir,
        "onn" to R.drawable.brand_logo_onn,
        "panasonic" to R.drawable.brand_logo_panasonic,
        "pdi" to R.drawable.brand_logo_pdi,
        "philips" to R.drawable.brand_logo_philips,
        "pioneer" to R.drawable.brand_logo_pioneer,
        "prismplus" to R.drawable.brand_logo_prismplus,
        "rca" to R.drawable.brand_logo_rca,
        "roku" to R.drawable.brand_logo_roku,
        "samsung" to R.drawable.brand_logo_samsung,
        "sanyo" to R.drawable.brand_logo_sanyo,
        "sceptre" to R.drawable.brand_logo_sceptre,
        "seiki" to R.drawable.brand_logo_seiki,
        "sencor" to R.drawable.brand_logo_sencor,
        "sharp" to R.drawable.brand_logo_sharp,
        "skyvue" to R.drawable.brand_logo_skyvue,
        "soniq" to R.drawable.brand_logo_soniq,
        "sony" to R.drawable.brand_logo_sony,
        "strong" to R.drawable.brand_logo_strong,
        "sunbrite" to R.drawable.brand_logo_sunbrite,
        "supra" to R.drawable.brand_logo_supra,
        "sweex" to R.drawable.brand_logo_sweex,
        "tcl" to R.drawable.brand_logo_tcl,
        "technika" to R.drawable.brand_logo_technika,
        "telecontrole" to R.drawable.brand_logo_telecontrole,
        "telefunken" to R.drawable.brand_logo_telefunken,
        "telekom" to R.drawable.brand_logo_telekom,
        "thomson" to R.drawable.brand_logo_thomson,
        "toshiba" to R.drawable.brand_logo_toshiba,
        "viewsonic" to R.drawable.brand_logo_viewsonic,
        "vitec" to R.drawable.brand_logo_vitec,
        "vizio" to R.drawable.brand_logo_vizio,
        "westinghouse" to R.drawable.brand_logo_westinghouse,
        "xiaomi" to R.drawable.brand_logo_xiaomi,
        "zenith" to R.drawable.brand_logo_zenith,
    )

    fun logoForName(name: String): Int? = logos[name.brandLogoKey()]
}

fun String.brandLogoKey(): String = lowercase().filter { it.isLetterOrDigit() }
